[project]
name = "merlin-track-position"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "h5netcdf>=1.8.1",
    "h5py>=3.15.1",
    "ipykernel>=7.2.0",
    "numpy>=2.4.4",
    "pypylon>=26.4.1",
    "pyqt6>=6.11.0",
    "pyqtgraph>=0.14.0",
    "qtpy>=2.4.3",
    "scikit-image>=0.26.0",
    "scipy>=1.17.1",
    "xarray>=2026.4.0",
]

[build-system]
requires = ["uv_build>=0.11.11,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
